when:
  event: [push, manual]
  branch: main

steps:
  validate:
    image: alpine:3.19
    commands:
      - apk add --no-cache yamllint yq
      - echo "=== Validating YAML files ==="
      - yamllint stacks/ || echo "YAML warnings (non-blocking)"
      - echo "=== Validating stack files ==="
      - for f in stacks/*.yml; do echo "Checking $f"; yq eval "." "$f" > /dev/null && echo "  Valid"; done

  deploy:
    image: alpine:3.19
    commands:
      - apk add --no-cache openssh-client docker-cli
      - mkdir -p ~/.ssh
      - echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519
      - ssh-keyscan -H 192.168.50.248 >> ~/.ssh/known_hosts 2>/dev/null
      - export DOCKER_HOST=ssh://mooseadmin@192.168.50.248
      - echo "=== Deploying stacks to Swarm ==="
      - |
        for stack in stacks/*.yml; do
          name=$(basename "$stack" .yml)
          echo "Deploying $name..."
          docker stack deploy -c "$stack" "$name"
        done
      - echo "=== Current stacks ==="
      - docker stack ls
    secrets: [deploy_key]
    depends_on: [validate]

labels:
  size: 2
