# Woodpecker CI Pipeline for Homelab Infrastructure
# This pipeline validates configurations and tests deployments

when:
  - event: [push, pull_request, manual]
    branch: [main, develop, feature/*]

steps:
  # Step 1: Validate YAML files
  validate-yaml:
    image: alpine:3.19
    commands:
      - apk add --no-cache yamllint
      - echo "Validating YAML files..."
      - find . -name "*.yml" -o -name "*.yaml" | grep -v ".git" | xargs yamllint -d "{extends: default, rules: {line-length: disable}}" || echo "YAML validation found issues"
    when:
      - event: [push, pull_request, manual]

  # Step 2: Validate Docker Compose files
  validate-compose:
    image: docker:27-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "Validating Docker Compose files..."
      - |
        for compose_file in $(find . -name "docker-compose.yml" -o -name "compose.yml"); do
          echo "Checking $compose_file"
          docker compose -f "$compose_file" config --quiet || echo "Warning: $compose_file has issues"
        done
    when:
      - event: [push, pull_request, manual]

  # Step 3: Test script syntax
  validate-scripts:
    image: alpine:3.19
    commands:
      - apk add --no-cache bash shellcheck
      - echo "Validating shell scripts..."
      - find ./scripts -name "*.sh" -exec shellcheck {} \; || echo "ShellCheck found issues"
    when:
      - event: [push, pull_request, manual]
      - path: "scripts/**"

  # Step 4: Display environment info
  environment-info:
    image: alpine:3.19
    commands:
      - echo "=== Build Environment ==="
      - echo "Runner: $(uname -m)"
      - echo "OS: $(cat /etc/os-release | grep PRETTY_NAME)"
      - echo "Disk: $(df -h / | tail -1)"
      - echo "Memory: $(free -h | grep Mem)"
      - echo "Agent: Pi 4 CI Controller"
    when:
      - event: [push, pull_request, manual]

labels:
  platform: linux/arm64
  docker: true
