when:
  event: [push, pull_request, manual]
  branch: [main, develop, feature/*]

steps:
  validate-yaml:
    image: alpine:3.19
    commands:
      - apk add --no-cache yamllint
      - echo "Validating YAML files..."
      - yamllint . || echo "YAML validation found issues (non-blocking)"

  validate-compose:
    image: alpine:3.19
    commands:
      - apk add --no-cache yq
      - echo "Validating Docker Compose files..."
      - |
        for compose_file in $(find . -name "docker-compose.yml" -o -name "compose.yml"); do
          echo "Checking $compose_file"
          yq eval '.' "$compose_file" > /dev/null && echo "  Valid YAML" || echo "  Invalid YAML"
        done

  validate-scripts:
    image: alpine:3.19
    commands:
      - apk add --no-cache bash shellcheck
      - echo "Validating shell scripts..."
      - find ./scripts -name "*.sh" -exec shellcheck {} \; || echo "ShellCheck found issues"
    when:
      path: "scripts/**"

  environment-info:
    image: alpine:3.19
    commands:
      - echo "=== Build Environment ==="
      - echo "Runner is $(uname -m)"
      - cat /etc/os-release | grep PRETTY_NAME
      - df -h / | tail -1
      - free -h | grep Mem
      - echo "Agent Pi 4 CI Controller"

labels:
  platform: linux/arm64
  docker: true
