when:
  event: [push, pull_request, manual]
  branch: [main, develop, feature/*]

steps:
  validate-yaml:
    image: alpine:3.19
    commands:
      - apk add --no-cache yamllint
      - echo "=== Validating YAML files ==="
      - yamllint . || echo "YAML warnings found (non-blocking)"

  validate-compose:
    image: alpine:3.19
    commands:
      - apk add --no-cache yq
      - echo "=== Validating Docker Compose files ==="
      - find ./devices -name "docker-compose.yml" -exec sh -c 'echo "Checking {}"; yq eval "." "{}" > /dev/null && echo "  Valid" || echo "  Invalid"' \;

  validate-scripts:
    image: alpine:3.19
    commands:
      - apk add --no-cache bash shellcheck
      - echo "=== Validating shell scripts ==="
      - find ./scripts -name "*.sh" -exec shellcheck {} \; || echo "ShellCheck warnings found"

  check-secrets:
    image: alpine:3.19
    commands:
      - echo "=== Checking for leaked secrets ==="
      - "! grep -r 'tskey-auth-' --include='*.yml' . 2>/dev/null | grep -v example || echo 'Warning: possible Tailscale key'"
      - echo "Secret check complete"

  environment-info:
    image: alpine:3.19
    commands:
      - echo "=== Build Environment ==="
      - uname -m
      - cat /etc/os-release | grep PRETTY_NAME
      - date

  deploy-info:
    image: alpine:3.19
    commands:
      - echo "=== Deployment Info ==="
      - echo "Woodpecker runs on Pi 4 at 192.168.50.183"
      - echo "Services are managed via docker compose"
    when:
      branch: main
      event: push

labels:
  platform: linux/arm64
  docker: true
