version: "3.8"

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - "13378:80"
    volumes:
      - audiobookshelf_config:/config
      - audiobookshelf_metadata:/metadata
      - /mnt/drive1/Media/Audiobooks:/audiobooks
      - /mnt/drive1/Media/Podcasts:/podcasts
    environment:
      - TZ=America/Denver

volumes:
  audiobookshelf_config:
  audiobookshelf_metadata:
