version: "3.8"

services:
  pihole:
    image: pihole/pihole:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: America/Denver
      FTLCONF_webserver_api_password: scripture
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1

volumes:
  pihole_data:
  dnsmasq_data:
