version: "3.8"

services:
  agent:
    image: portainer/agent:latest
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network

  portainer:
    image: portainer/portainer-ce:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 256M
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    command: -H tcp://tasks.agent:9001 --tlsskipverify

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
